import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { readFile } from 'node:fs/promises';
import { createPlanService, validateIntake } from './api.js';

const port = Number(process.env.PORT ?? 4173);
const plans = createPlanService();
const json = (response: ServerResponse, status: number, value: unknown) => { response.writeHead(status, { 'content-type': 'application/json; charset=utf-8' }); response.end(JSON.stringify(value)); };
async function readBody(request: IncomingMessage): Promise<unknown> { let raw = ''; for await (const chunk of request) raw += chunk; return JSON.parse(raw || '{}'); }
const page = '<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tatil Modu</title><style>:root{font-family:Inter,system-ui,sans-serif;color:#17211b;background:#f4f7f2;line-height:1.5}*{box-sizing:border-box}body{margin:0}.shell{max-width:980px;margin:auto;padding:28px 18px 60px}.eyebrow{color:#47735b;font-weight:700;letter-spacing:.08em;text-transform:uppercase;font-size:.75rem}h1{font-size:clamp(2rem,5vw,4rem);line-height:1.05;margin:.35rem 0 1rem;max-width:700px}h2{margin-top:0}.lede{font-size:1.1rem;max-width:650px;color:#506057}.card{background:white;border:1px solid #dbe5dc;border-radius:20px;padding:22px;box-shadow:0 8px 28px #1c3c2710;margin-top:18px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}@media(max-width:680px){.grid{grid-template-columns:1fr}}label{display:grid;gap:6px;font-weight:650}input{border:1px solid #b8c8bb;border-radius:10px;padding:12px;font:inherit;background:#fbfdfb}button{border:0;border-radius:999px;padding:12px 17px;background:#1f6b43;color:white;font:inherit;font-weight:700;cursor:pointer;margin:8px 8px 0 0}button.secondary{background:#e4eee6;color:#1f5135}button.danger{background:#9d3d37}.pill{display:inline-flex;border-radius:999px;padding:4px 10px;background:#e6f2e8;color:#23613d;font-size:.85rem;font-weight:700}.muted{color:#66766c}.notice{border-left:4px solid #e1a735;background:#fff8e6;padding:12px 14px;border-radius:8px}.day{border-top:1px solid #e1e9e2;padding-top:18px;margin-top:18px}.block{padding:11px 0;border-bottom:1px solid #edf2ed}.block strong{display:block;color:#47735b}.alternatives{display:flex;flex-wrap:wrap;gap:8px}.alternative{background:#eef5ef;border-radius:10px;padding:8px 10px}</style></head><body><main class="shell"><div class="eyebrow">Tatil Modu · doğrulanmış planlama</div><h1>Aileniz için daha sakin bir tatil planı.</h1><p class="lede">Intake verisi gerçek API’ye gönderilir; planlama durumu polling ile izlenir.</p><section id="app" class="card"></section></main><script type="module" src="/client.js"></script></body></html>';
async function handler(request: IncomingMessage, response: ServerResponse): Promise<void> {
  const url = new URL(request.url ?? '/', 'http://127.0.0.1');
  if (url.pathname === '/health') return json(response, 200, { status: 'ok' });
  if (url.pathname === '/client.js') { response.writeHead(200, { 'content-type': 'text/javascript; charset=utf-8' }); response.end(await readFile(new URL('./client.js', import.meta.url), 'utf8')); return; }
  if (url.pathname === '/api/plans' && request.method === 'POST') { try { const job = plans.start(validateIntake(await readBody(request))); return json(response, 202, { id: job.id, status: job.status, pollUrl: '/api/plans/' + job.id }); } catch (error) { return json(response, 400, { error: error instanceof Error ? error.message : 'Invalid request.' }); } }
  const match = url.pathname.match(/^\/api\/plans\/([^/]+)$/);
  if (match && request.method === 'GET') { const id = match[1]; const job = id ? plans.get(id) : undefined; return job ? json(response, 200, job) : json(response, 404, { error: 'Plan not found.' }); }
  response.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }); response.end(page);
}
createServer((request, response) => { void handler(request, response); }).listen(port, '127.0.0.1', () => console.log('Tatil Modu web listening on http://127.0.0.1:' + port));
