import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { runHeadlessTripPlan, type HeadlessTripPlanResult } from '../../../packages/orchestrator/src/index.js';
import { toUiPlanViewModel, type UiPlanViewModel } from './ui-adapter.js';

const port = Number(process.env.PORT ?? 4173);
const input = { traceId: 'web-fixture-001', origin: 'Istanbul', targetRegion: 'Marmara', durationDays: 2, childrenAges: [2, 6], budgetAmount: 40000, maxRadiusKm: 150, lowFatigueRequired: true, middayRestRequired: true, womenOnlyBeachRequiredWhenSeaRecommended: true,
  candidatePool: [{ candidateId: 'candidate-yalova', name: 'Yalova', type: 'mixed' as const, relationToTarget: 'primary' as const, estimatedDistanceBucket: '50_100_km' as const, likelyTripRole: 'base_stay' as const, familyRelevanceHypothesis: 'Short transfer and family rest options.', seaRelevant: true, fatigueRisk: 'low' as const }],
  routes: [{ destinationId: 'candidate-yalova', destinationName: 'Yalova', exactDistanceKm: 92, exactDriveTimeMinutes: 85, parkingAvailable: true, trafficRisk: 'low' as const, evidenceIds: { exactDistance: 'route-distance-001', exactDriveTime: 'route-duration-001', parkingAvailability: 'parking-001', liveTraffic: 'traffic-001' } }],
  evidence: { womenOnlyBeach: { evidenceId: 'official-facility-001', sourceType: 'official_facility' as const } } };

function view(result: HeadlessTripPlanResult): UiPlanViewModel {
  if (!result.finalResponse) return { status: 'blocked', title: 'Plan oluşturulamadı', summary: 'Gerekli doğrulama tamamlanmadan final plan gösterilmez.', durationDays: input.durationDays, travelStyle: 'family_low_fatigue', privacyConstraintActive: true, days: [], disclosures: [], blockers: result.verification.hard_blockers, confidence: result.verification.confidence.value, confidenceReasons: result.verification.confidence.reasons };
  return toUiPlanViewModel(result.finalResponse);
}
const completed = view(runHeadlessTripPlan(input));
const { evidence: _evidence, ...inputWithoutEvidence } = input;
const blocked = view(runHeadlessTripPlan(inputWithoutEvidence));
const escapeJson = (value: unknown) => JSON.stringify(value).replaceAll('<', '\\u003c');

function page(initialState: 'intake' | 'completed' | 'blocked'): string {
  return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tatil Modu</title><style>
  :root{font-family:Inter,system-ui,sans-serif;color:#17211b;background:#f4f7f2;line-height:1.5}*{box-sizing:border-box}body{margin:0}.shell{max-width:980px;margin:auto;padding:28px 18px 60px}.eyebrow{color:#47735b;font-weight:700;letter-spacing:.08em;text-transform:uppercase;font-size:.75rem}h1{font-size:clamp(2rem,5vw,4rem);line-height:1.05;margin:.35rem 0 1rem;max-width:700px}h2{margin-top:0}.lede{font-size:1.1rem;max-width:650px;color:#506057}.card{background:white;border:1px solid #dbe5dc;border-radius:20px;padding:22px;box-shadow:0 8px 28px #1c3c2710;margin-top:18px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}@media(max-width:680px){.grid{grid-template-columns:1fr}}label{display:grid;gap:6px;font-weight:650}input{border:1px solid #b8c8bb;border-radius:10px;padding:12px;font:inherit;background:#fbfdfb}button{border:0;border-radius:999px;padding:12px 17px;background:#1f6b43;color:white;font:inherit;font-weight:700;cursor:pointer;margin:8px 8px 0 0}button.secondary{background:#e4eee6;color:#1f5135}button.danger{background:#9d3d37}.pill{display:inline-flex;border-radius:999px;padding:4px 10px;background:#e6f2e8;color:#23613d;font-size:.85rem;font-weight:700}.pill.blocked{background:#fde9e6;color:#9d3d37}.muted{color:#66766c}.notice{border-left:4px solid #e1a735;background:#fff8e6;padding:12px 14px;border-radius:8px}.blocker{border-left-color:#b5423c;background:#fff0ee}.day{border-top:1px solid #e1e9e2;padding-top:18px;margin-top:18px}.block{padding:11px 0;border-bottom:1px solid #edf2ed}.block:last-child{border-bottom:0}.block strong{display:block;color:#47735b}.alternatives{display:flex;flex-wrap:wrap;gap:8px}.alternative{background:#eef5ef;border-radius:10px;padding:8px 10px}</style></head><body><main class="shell"><div class="eyebrow">Tatil Modu · doğrulanmış planlama</div><h1>Aileniz için daha sakin bir tatil planı.</h1><p class="lede">Önce sınırlarınızı netleştirelim; sonra doğrulama durumunu açıkça gösteren uygulanabilir bir plan oluşturalım.</p><section id="app" class="card"></section></main><script>window.__TATIL_MODU__=${escapeJson({ completed, blocked })};</script><script>
  const data=window.__TATIL_MODU__,app=document.querySelector('#app');let state='${initialState}';
  function render(){if(state==='intake'){app.innerHTML='<h2>Planınızı anlatın</h2><p class="muted">Kritik bilgileri kısa tutuyoruz; geri kalanını plan sırasında netleştirebilirsiniz.</p><div class="grid"><label>Başlangıç noktası<input data-testid="origin" value="Istanbul"></label><label>Hedef bölge<input data-testid="region" value="Marmara"></label><label>Kaç gün?<input data-testid="days" type="number" value="2"></label><label>Bütçe (₺)<input data-testid="budget" type="number" value="40000"></label></div><button data-action="confirm">Devam et</button>';return}if(state==='confirm'){app.innerHTML='<h2>Sizi doğru anladık mı?</h2><p class="muted">Planı çalıştırmadan önce değiştirilebilir sınırları onaylayın.</p><div class="notice"><strong>Olmazsa olmazlar</strong><ul><li>Çocuklar için düşük yorgunluk</li><li>Öğle dinlenme aralığı</li><li>Deniz önerilirse kadınlara özel plaj kanıtı</li></ul></div><p><span class="pill">2 gün</span> <span class="pill">₺40.000 bütçe</span> <span class="pill">Marmara</span></p><button data-action="plan">Planı oluştur</button><button class="secondary" data-action="back">Düzenle</button>';return}if(state==='loading'){app.innerHTML='<h2>Plan hazırlanıyor…</h2><p class="muted" aria-live="polite">Sınırlar, aile uygunluğu, rota ve doğrulama birlikte kontrol ediliyor.</p><div class="notice">Doğrulama tamamlanana kadar final plan gösterilmez.</div>';setTimeout(()=>{state='completed';history.pushState({},'', '/plan');render()},650);return}app.innerHTML=plan(data[state])}
  function plan(p){const isBlocked=p.status==='blocked';return '<div aria-live="polite"><span class="pill '+(isBlocked?'blocked':'')+'">'+(isBlocked?'Doğrulama engeli':'Doğrulandı')+'</span><h2>'+p.title+'</h2><p class="lede">'+p.summary+'</p>'+(isBlocked?'<div class="notice blocker" role="alert"><strong>Plan durduruldu</strong><p>Gerekli kanıt bulunamadığı için final plan gösterilmiyor.</p><ul>'+p.blockers.map(x=>'<li>'+x+'</li>').join('')+'</ul></div>':'<div class="grid"><div><strong>Süre</strong><br>'+p.durationDays+' gün</div><div><strong>Tempo</strong><br>'+p.travelStyle+'</div></div><div class="notice"><strong>Verification</strong><p>'+p.disclosures.map(x=>x.message+' ('+x.status+')').join('<br>')+'</p></div>'+p.days.map(d=>'<article class="day"><h3>Gün '+d.dayNumber+' · '+d.theme+'</h3>'+d.blocks.map(b=>'<div class="block"><strong>'+b.label+'</strong>'+b.title+'<div class="muted">'+b.notes.join(' ')+'</div></div>').join('')+'<p><strong>Alternatifler</strong></p><div class="alternatives">'+d.alternatives.map(x=>'<span class="alternative">'+x+'</span>').join('')+'</div></article>').join('')+'<button class="danger" data-action="blocked">Kanıt eksik senaryosunu göster</button><button class="secondary" data-action="back">Yeni plan</button></div>')}
  app.addEventListener('click',e=>{const action=e.target.closest('button')?.dataset.action;if(!action)return;if(action==='confirm')state='confirm';if(action==='plan')state='loading';if(action==='blocked'){state='blocked';history.pushState({},'', '/blocked')}if(action==='back'){state='intake';history.pushState({},'', '/')}render()});window.addEventListener('popstate',()=>{state=location.pathname==='/plan'?'completed':location.pathname==='/blocked'?'blocked':'intake';render()});render();</script></body></html>`;
}

function handler(request: IncomingMessage, response: ServerResponse): void {
  const pathname = new URL(request.url ?? '/', 'http://127.0.0.1').pathname;
  if (pathname === '/health') { response.writeHead(200, { 'content-type': 'application/json' }); response.end(JSON.stringify({ status: 'ok' })); return; }
  const state = pathname === '/plan' ? 'completed' : pathname === '/blocked' ? 'blocked' : 'intake';
  response.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }); response.end(page(state));
}

createServer(handler).listen(port, '127.0.0.1', () => console.log(`Tatil Modu web listening on http://127.0.0.1:${port}`));
